### ISSUE TITLE
I would like all new repositories to auto-select

### ISSUE THREAD

**Issue by SebastienViel** [dcmeglio/hubitat-packagemanager#102]
There are more and more new repositories.  I would like not to have to go in and always manually select the new ones.  Is there a way to automatically have them all included?  If not, I would like to request this new feature.

Thanks!

**Comment by neonturbo** [comment]
Agree. That would make things better. I missed a couple good apps because I didn't realize that someone new was added to the list.

**Comment by dcmeglio** [comment]
Agreed, it is a bug that it isn't currently. I *think* I may have fixed it going forward in 1.4.3, but I'm not 100% sure so I'm leaving this open for now. It will NOT go back and check ones that weren't already checked, but as new ones are added it should auto-check them... I hope

**Comment by dcmeglio** [comment]
Did thomas.c.howard's repo get checked for you automatically in 1.4.3? It did for me.

**Comment by neonturbo** [comment]
I will give that a firm, I don't know.

I remember checking at least one of them, I don't know who it was. And I don't know whether it was 1.43 or previous.

I am really not helpful, sorry!   :(

But they are all checked now. Next time someone adds a repository will tell I guess.

**Comment by neonturbo** [comment]
Actually I take the above back. Somehow HPM didn't detect 1.4.3 update, I had to do it manually. 

And thomas.c.howard's was checked by default.

**Comment by dcmeglio** [comment]
I believe this is fixed, Arn Burkhoff's repository also auto-enabled for me. Marking as closed for now and if it happens again we can reopen.

**Comment by SebastienViel** [comment]
Yes, I don’t seem to have to select new repositories anymore. Will let you know if this changes.  Thanks!
