### ISSUE TITLE
Hub version 2.2.0.130 - Package Manager will not open

### ISSUE THREAD

**Issue by SebastienViel** [dcmeglio/hubitat-packagemanager#103]
On a hub with version 2.2.0.130, Package Manager will not open.  Getting:

### Unexpected Error
An unexpected error has occurred trying to load the app. Check Logs for more information.

No related messages in the log.

**Comment by PrayerfulDrop** [comment]
This is a known issue and was posted on the forums. You will need to manually install the update from the github repository to acquire the latest code with hotfix.

**Comment by SebastienViel** [comment]
Okay, no problem then.  Thanks!  (I should have checked the forum first...  sorry for that...)
