### ISSUE TITLE
Search not providing correct results

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#104]
Search is not looking at the full name of the application/driver to pull results.  When doing a search for weather the results do not display NOAA Weather Alerts.

**Comment by dcmeglio** [comment]
Search filters out apps you already have installed. My gut is, since you wrote it, you have it installed! I just uninstalled it and searched and it shows up:

![image](https://user-images.githubusercontent.com/21957250/82589653-75001600-9b6a-11ea-985d-23e5b6aa88b5.png)

**Comment by dcmeglio** [comment]
Any chance you were able to confirm this is working? I'd like to close it out but not before being sure.

**Comment by dcmeglio** [comment]
I'm closing this out as I believe it is working correctly. If you experience the issue again, please let me know.
