### ISSUE TITLE
Beta code always trumps RTM code

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#109]
HPM does not take into account version differences between RTM and Beta.  If RTM is a higher version number than the Beta that code should be deployed instead of the Beta branch.  Also there is no way to install RTM code if the selection in settings is selected for pre-release code.

**Comment by dcmeglio** [comment]
Definitely a bug, it's actually supposed to grab the "release" version even if the version #'s equal.

**Comment by dcmeglio** [comment]
Headed down the rabbit hole... Discovered 2-3 related bugs, should have this fixed for the next version.

**Comment by dcmeglio** [comment]
Took a bunch of work (not sure how I ever thought that would work properly!) I wouldn't mind extra testing of the various changes, the code is available at https://raw.githubusercontent.com/dcmeglio/hubitat-packagemanager/1.5.0-dev/apps/Package_Manager.groovy
