### ISSUE TITLE
Search should include what has been installed

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#110]
When searching I would like to see everything come back for the search results verses reducing the list based on what is installed.  A better visual would be to list all applications and have a (Installed) next to the names of the apps/drivers that actually have been installed.  Tends to be the standard for application store searches.

**Comment by dcmeglio** [comment]
I have a cool thought for how I want to implement this. I want to redo the results a little bit to be more useful and also use the same UI for categories and search. I'm hoping to have something together later today or tomorrow.

**Comment by dcmeglio** [comment]
This will be added in 1.5.0 It will look like:

![image](https://user-images.githubusercontent.com/21957250/83580236-8271b480-a509-11ea-873d-d273ccd7f88c.png)

A checkmark represents that it is installed, download is to install a new package, and there are also zwave/zigbee/cloud/lan icons that can tell you the type of package
