### ISSUE TITLE
Two Issues with Installing from a URL

### ISSUE THREAD

**Issue by YetAnotherBugHunter** [dcmeglio/hubitat-packagemanager#119]
First Issue:

When I try to install this https://github.com/arnbme/nyckelharpa/blob/master/packageManifest.json package via a URL I get the following error message:

**Invalid Package File
https://github.com/arnbme/nyckelharpa/blob/master/packageManifest.json does not appear to be a valid Hubitat Package or does not exist.**

I've check and that URL does correspond to a package manifest.

Second Issue (related to the first issue)

After getting the error from issue 1 above, I get the below error when I click on the Main Menu button:

**Unexpected Error
An unexpected error has occurred trying to load the app. Check Logs for more information.**

**Comment by nyocker** [comment]
I have the same issue, please help

**Comment by dcmeglio** [comment]
You need to use the raw url. The url you pasted is not a json file, it goes to the GitHub website. The correct url would be https://raw.githubusercontent.com/arnbme/nyckelharpa/master/packageManifest.json

**Comment by YetAnotherBugHunter** [comment]
Thanks for the clarification.
