### ISSUE TITLE
java.lang.NullPointerException: Cannot get property 'repositories' on null object on line 3433 (prefSettings)

### ISSUE THREAD

**Issue by k3vmcd** [dcmeglio/hubitat-packagemanager#121]
https://github.com/dcmeglio/hubitat-packagemanager/blob/8cf858c34b268b5aed22a3108e44ba19e9fa7b75/apps/Package_Manager.groovy#L3433

Cannot start app.
Error: `java.lang.NullPointerException: Cannot get property 'repositories' on null object on line 3433 (prefSettings)`

Steps to reproduce:
1. Added app code to Hubitat
2. Added User App and set up initial preferences
3. Added Inovelli device code through app
4. Tried to add custom github repo (misconfiguration, I tried to add github url without manifest file)
5. Navigated away from app, installed custom device code separately
6. Revisiting app - app crash with above error
7. Full Reset Hubitat, app still will not start up with same error

**Comment by k3vmcd** [comment]
I think I traced this to a DNS error within my network

**Comment by dcantatore** [comment]
@k3vmcd - Hate to necro this thread but any idea what that might have been?

**Comment by k3vmcd** [comment]
@dcantatore Too much time has passed for me to remember specifically, and I've since sold my Hubitat and replaced with HomeAssistant.

At the time, my 10/3/2020 comment is referring to my edits to several settings in my pfsense firewall that I was pretty confident was the solution. I have several firewall configurations and filters in place to block certain traffic, and my IoT devices are on a separate vlan. I believe the IoT vlan originally wasn't getting the DNS for this routed correctly, but I also did a few reinstalls of Hubitat & Hubitat app code at the same time, so somewhere in all of that this one resolved.
