### ISSUE TITLE
Add ability for users to go back during menu options

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#22]
If you make a mistake or browsing the repositories for apps you may want to go back to another category.

**Comment by dcmeglio** [comment]
Agreed. I think for the category vs. app part @bptworld  suggested putting them on a single screen which sounds great. But I agree having some kind of back button on other screens would help.

**Comment by bptworld** [comment]
I created a href button on each page linking back to the Main menu.  Waiting to PR until my other one goes through.  
![Screenshot 2020-04-10 at 3 10 52 PM](https://user-images.githubusercontent.com/23482934/79016765-c6fe5680-7b3d-11ea-83c0-dcf33c293c25.png)

**Comment by dcmeglio** [comment]
Looks good. I made a couple small changes but merged your previous PR.

**Comment by dcmeglio** [comment]
Interesting thing - apparently an href doesn't work if there are required fields on the page that aren't filled out? I just learned that testing your change. Wonder if there is a way around that?

**Comment by bptworld** [comment]
Not that I could find.  I looked at both HE and ST docs for href and nothing is mentioned about it.
