### ISSUE TITLE
Check to see if app/driver is still in use

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#24]
If app/driver is being used the app cannot uninstall the code.

**Comment by dcmeglio** [comment]
@PrayerfulDrop Could you help me understand what this one means? You're saying the uninstall failed if it was in use? Also what does it mean for an app to be in use? The only thing I know that HE reports as "in use" are devices

**Comment by dcmeglio** [comment]
Ok I was able to confirm this.
