### ISSUE TITLE
Change UI on how apps/drivers are selected

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#25]
It would be nice to see a list of what is available prior to making a selection.  The categories are not intuitive and apps/drivers could be anywhere.  A simple list of the repository results broken into categories could be a better UI.  Also check boxes next to desired installs would be better than a drop-down selection of only (1) app.

**Comment by dcmeglio** [comment]
@PrayerfulDrop I merged in a patch from @bptworld that makes it a lot better. Let me know what you think.

**Comment by PrayerfulDrop** [comment]
It is better than prior.  I will work on a new UI concept and see if you like.

**Comment by bptworld** [comment]
I've been playing around with this some more.  Can now sort the apps list by app or author.

**Comment by bptworld** [comment]
Added pull request for sorting packages

**Comment by PrayerfulDrop** [comment]
This is much better than previous versions. Great job BPTWorld!
