### ISSUE TITLE
Option for automatic updates on each app

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#26]
Instead of user intervention each time an update is available it would be good to provide in the daily update process to automatically update those apps a user selects.  Ideally, this would be granular so larger apps may wish to be a N-1 manually updated whereas a weather app a user may want updated automatically.

**Comment by dcmeglio** [comment]
Hmm I like this idea, but I think there is more to it so probably better for a v2. The reason I say this is I then think we'll need notification settings (you probably want to be notified of any updates that fail -- and maybe even succeed). Definitely needs to be per package as you suggest, sometimes developers release bad updates and I wouldn't want to just wake up to a broken hub :)

**Comment by dcmeglio** [comment]
- [] #60 
- [] #61 
- [] #62

**Comment by dcmeglio** [comment]
- [ ] #60
- [ ] #61 
- [ ] #62

**Comment by dcmeglio** [comment]
Found a nice easy way to get this working: 
![image](https://user-images.githubusercontent.com/21957250/79926236-60fdb300-840a-11ea-963e-02d642bd5a65.png)

**Comment by PrayerfulDrop** [comment]
Like it
