### ISSUE TITLE
Instructions of use in the app itself

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#27]
Provide instructions and expectations of what the app can do to remove questions in the community

**Comment by dcmeglio** [comment]
@PrayerfulDrop  I did create a README.md. Anything in particular you think is missing?

**Comment by PrayerfulDrop** [comment]
Just thinking of the n00bie user who might struggle using the app itself and forget the readme.md file.  Can be a v2.

**Comment by dcmeglio** [comment]
Ah now I get it, you meant in the app itself... Guess it would help if I could read! As a note, and I know it's a newer HE feature so new users might not even see it, I did link to the readme from the ? icon displayed in the app using the documentationLink setting.

**Comment by dcmeglio** [comment]
All of the text has been updated to be a lot more readable. I'm going to close this out and we can always add more specific issues if people get confused.
