### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by bptworld** [dcmeglio/hubitat-packagemanager#33]
Thinking we will need more categories... existing will get busy quickly. 

Of the top of my head...

Control = Lighting/Motion/presence/Locks
Convenience = catch all
Integrations =- devices/applications/services
Notifications = speakers/TTS/music
Security = presence/camera/sensors
Utility = Data/Button controllers/IR control

What's missing.... ?

**Comment by dcmeglio** [comment]
I agree. Honestly I hate categories because people will never guess correctly, but I don't really have a better solution...

I think that's a good start though. Anyone else have any suggestions?
