### ISSUE TITLE
Feature Request: List of all managed applications currently selected

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#40]
I have no idea what apps are currently being monitored.  A report page would be nice.

**Comment by dcmeglio** [comment]
So you mean something that says "these apps are managed" and "these drivers are managed"? I agree that'd be useful.

**Comment by PrayerfulDrop** [comment]
Or an these apps/drivers are currently installed.  Thinking longer term as this continues to grow ppl won’t remember what they installed but didn’t use.

**Comment by dcmeglio** [comment]
Makes sense. I added this.
