### ISSUE TITLE
Still creates duplicates!

### ISSUE THREAD

**Issue by SANdood** [dcmeglio/hubitat-packagemanager#48]
Are you making separate copies because the current version doesn't match or something?

This is in my test&dev, but it is still painful to recover from - I have to copy the new file content back into the old file content, then delete the new file

![image](https://user-images.githubusercontent.com/8018000/79245702-72612100-7e46-11ea-8185-1976f03191f2.png)

![image](https://user-images.githubusercontent.com/8018000/79245815-9886c100-7e46-11ea-8642-54f128c165a1.png)

...
app:25942020-04-14 11:51:05.410 am debugprefPkgView
app:25942020-04-14 11:50:58.316 am debugcalled true
app:25942020-04-14 11:50:42.516 am infoMatching up packages
app:25942020-04-14 11:50:42.143 am infoRefreshing RMoRobert (BertABCD1234)
app:25942020-04-14 11:50:41.710 am infoRefreshing storageaanarchy (SANdood)
app:25942020-04-14 11:50:39.052 am infoRefreshing dman2306
app:25942020-04-14 11:50:36.265 am warnFound a bad manifest https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Life360%20Tracker/packageManifest.json
app:25942020-04-14 11:50:33.104 am infoRefreshing BPTWorld
app:25942020-04-14 11:50:31.577 am infoRefreshing AaronW
app:25942020-04-14 11:50:29.977 am infoRetrieving list of installed drivers
app:25942020-04-14 11:50:29.456 am infoRetrieving list of installed apps
app:25942020-04-14 11:50:29.344 am debugPerforming Package Matching
app:25942020-04-14 11:50:26.446 am debugprefPkgMatchUp
app:25942020-04-14 11:50:23.337 am debugcalled true
app:25942020-04-14 11:50:20.269 am debugcalled false
app:25942020-04-14 11:50:20.182 am debugfalse
app:25942020-04-14 11:50:18.242 am infoInstalling Ecobee Suite Sensor
app:25942020-04-14 11:50:18.168 am debugtrue
app:25942020-04-14 11:50:16.172 am debugtrue
app:25942020-04-14 11:50:14.481 am debugtrue
app:25942020-04-14 11:50:12.462 am debugtrue
app:25942020-04-14 11:50:10.445 am debugtrue
app:25942020-04-14 11:50:08.605 am debugtrue
app:25942020-04-14 11:50:06.573 am debugtrue
app:25942020-04-14 11:50:04.632 am debugtrue
app:25942020-04-14 11:50:02.641 am debugtrue
app:25942020-04-14 11:50:01.150 am infoInstalling Ecobee Suite Thermostat
app:25942020-04-14 11:50:00.209 am debugtrue
app:25942020-04-14 11:49:58.811 am debugtrue
app:25942020-04-14 11:49:56.273 am debugtrue
app:25942020-04-14 11:49:54.810 am infoInstalling ecobee Suite Working From Home
app:25942020-04-14 11:49:54.183 am debugtrue
app:25942020-04-14 11:49:52.287 am debugtrue
app:25942020-04-14 11:49:50.177 am debugtrue
app:25942020-04-14 11:49:49.285 am infoInstalling ecobee Suite Thermal Comfort
app:25942020-04-14 11:49:48.212 am debugtrue
app:25942020-04-14 11:49:46.549 am debugtrue
app:25942020-04-14 11:49:44.282 am debugtrue
app:25942020-04-14 11:49:42.931 am debugtrue
app:25942020-04-14 11:49:40.879 am infoInstalling ecobee Suite Smart Zones
app:25942020-04-14 11:49:40.172 am debugtrue
app:25942020-04-14 11:49:38.206 am debugtrue
app:25942020-04-14 11:49:37.320 am infoInstalling ecobee Suite Smart Vents
app:25942020-04-14 11:49:36.177 am debugtrue
app:25942020-04-14 11:49:35.523 am infoInstalling ecobee Suite Smart Switches
app:25942020-04-14 11:49:34.400 am debugtrue
app:25942020-04-14 11:49:32.162 am debugtrue
app:25942020-04-14 11:49:31.347 am infoInstalling ecobee Suite Smart Room
app:25942020-04-14 11:49:30.193 am debugtrue
app:25942020-04-14 11:49:28.149 am debugtrue
app:25942020-04-14 11:49:26.606 am infoInstalling ecobee Suite Smart Mode
app:25942020-04-14 11:49:26.146 am debugtrue
app:25942020-04-14 11:49:24.381 am infoInstalling ecobee Suite Smart Humidity
app:25942020-04-14 11:49:24.349 am debugtrue
app:25942020-04-14 11:49:22.265 am debugtrue
app:25942020-04-14 11:49:21.325 am infoInstalling ecobee Suite Smart Circulation
app:25942020-04-14 11:49:20.240 am debugtrue
app:25942020-04-14 11:49:18.288 am infoInstalling ecobee Suite Routines
app:25942020-04-14 11:49:18.192 am debugtrue
app:25942020-04-14 11:49:16.207 am debugtrue
app:25942020-04-14 11:49:15.519 am infoInstalling ecobee Suite Quiet Time
app:25942020-04-14 11:49:14.219 am debugtrue
app:25942020-04-14 11:49:11.322 am debugtrue
app:25942020-04-14 11:49:09.458 am debugtrue
app:25942020-04-14 11:49:09.441 am infoInstalling ecobee Suite Open Contacts
app:25942020-04-14 11:49:07.260 am debugtrue
app:25942020-04-14 11:49:05.305 am debugtrue
app:25942020-04-14 11:49:03.211 am debugtrue
app:25942020-04-14 11:49:01.393 am debugtrue
app:25942020-04-14 11:49:00.236 am debugtrue
app:25942020-04-14 11:48:58.144 am debugtrue
app:25942020-04-14 11:48:56.193 am debugtrue
app:25942020-04-14 11:48:54.171 am debugtrue
app:25942020-04-14 11:48:52.395 am debugtrue
app:25942020-04-14 11:48:50.268 am debugtrue
app:25942020-04-14 11:48:48.166 am debugtrue
app:25942020-04-14 11:48:46.186 am debugtrue
app:25942020-04-14 11:48:44.661 am debugtrue
app:25942020-04-14 11:48:42.185 am debugtrue
app:25942020-04-14 11:48:40.345 am debugtrue
app:25942020-04-14 11:48:38.254 am debugtrue
app:25942020-04-14 11:48:36.259 am debugtrue
app:25942020-04-14 11:48:34.373 am debugtrue
app:25942020-04-14 11:48:32.448 am debugtrue
app:25942020-04-14 11:48:30.571 am debugtrue
app:25942020-04-14 11:48:28.267 am debugtrue
app:25942020-04-14 11:48:26.794 am debugtrue
app:25942020-04-14 11:48:24.773 am debugtrue
app:25942020-04-14 11:48:22.505 am debugtrue
app:25942020-04-14 11:48:20.537 am debugtrue
app:25942020-04-14 11:48:18.230 am debugtrue
app:25942020-04-14 11:48:16.630 am debugtrue
app:25942020-04-14 11:48:14.198 am debugtrue
app:25942020-04-14 11:48:11.269 am debugtrue
app:25942020-04-14 11:48:09.432 am debugtrue
app:25942020-04-14 11:48:07.241 am debugtrue
app:25942020-04-14 11:48:05.211 am debugtrue
app:25942020-04-14 11:48:03.294 am debugtrue
app:25942020-04-14 11:48:01.208 am debugtrue
app:25942020-04-14 11:47:59.208 am debugtrue
app:25942020-04-14 11:47:57.463 am infoInstalling Ecobee Suite Manager
app:25942020-04-14 11:47:57.190 am debugtrue
app:25942020-04-14 11:47:57.083 am infoDownloading Ecobee Suite Sensor
app:25942020-04-14 11:47:56.843 am infoDownloading Ecobee Suite Thermostat
app:25942020-04-14 11:47:56.609 am infoDownloading ecobee Suite Working From Home
app:25942020-04-14 11:47:56.326 am infoDownloading ecobee Suite Thermal Comfort
app:25942020-04-14 11:47:56.108 am infoDownloading ecobee Suite Smart Zones
app:25942020-04-14 11:47:55.885 am infoDownloading ecobee Suite Smart Vents
app:25942020-04-14 11:47:55.466 am infoDownloading ecobee Suite Smart Switches
app:25942020-04-14 11:47:55.237 am infoDownloading ecobee Suite Smart Room
app:25942020-04-14 11:47:55.190 am debugtrue
app:25942020-04-14 11:47:54.996 am infoDownloading ecobee Suite Smart Mode
app:25942020-04-14 11:47:54.778 am infoDownloading ecobee Suite Smart Humidity
app:25942020-04-14 11:47:54.562 am infoDownloading ecobee Suite Smart Circulation
app:25942020-04-14 11:47:54.317 am infoDownloading ecobee Suite Routines
app:25942020-04-14 11:47:53.900 am infoDownloading ecobee Suite Quiet Time
app:25942020-04-14 11:47:53.602 am infoDownloading ecobee Suite Open Contacts
app:25942020-04-14 11:47:53.265 am infoDownloading Ecobee Suite Manager
app:25942020-04-14 11:47:53.081 am debugInstall beginning
app:25942020-04-14 11:47:53.079 am debugprefInstall
app:25942020-04-14 11:47:53.053 am debug
app:25942020-04-14 11:47:44.368 am debugprefInstallVerify
app:25942020-04-14 11:47:42.870 am debugprefInstallChoices
app:25942020-04-14 11:47:37.861 am debugprefPkgInstallUrl
app:25942020-04-14 11:47:33.986 am debugprefPkgInstall
app:25942020-04-14 11:47:28.899 am debugcalled true
app:25942020-04-14 11:47:23.675 am debugprefPkgModify
app:25942020-04-14 11:47:17.729 am debugcalled true
app:25942020-04-14 11:47:01.177 am debugprefPkgView
app:25942020-04-14 11:46:50.365 am debugcalled true
app:25942020-04-14 11:46:50.135 am debugRefreshing repository list
app:25942020-04-14 11:46:35.881 am debugcalled true
app:25942020-04-14 11:46:23.951 am debugprefInstallChoices
app:25942020-04-14 11:46:18.168 am debugprefPkgInstallUrl
app:25942020-04-14 11:46:10.834 am debugprefPkgInstall
app:25942020-04-14 11:45:58.488 am debugcalled true
app:25942020-04-14 11:45:52.207 am debugUpdates available
app:25942020-04-14 11:45:51.158 am debugUpdates found for package https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Follow%20Me/packageManifest.json
app:25942020-04-14 11:45:50.965 am infoChecking for updates for Follow Me
app:25942020-04-14 11:45:50.962 am debugUpdates found for driver https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-sensor.src/ecobee-suite-sensor.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 11:45:50.959 am debugUpdates found for driver https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-thermostat.src/ecobee-suite-thermostat.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 11:45:50.951 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-mode.src/ecobee-suite-smart-mode.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 11:45:50.947 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-circulation.src/ecobee-suite-smart-circulation.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 11:45:50.943 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-routines.src/ecobee-suite-routines.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 11:45:50.939 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-open-contacts.src/ecobee-suite-open-contacts.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 11:45:50.749 am infoChecking for updates for Ecobee Suite
app:25942020-04-14 11:45:50.579 am infoChecking for updates for PurpleAir Air Quality Station
app:25942020-04-14 11:45:50.576 am debugUpdates found for package https://raw.githubusercontent.com/dcmeglio/hubitat-packagemanager/master/packageManifest.json
app:25942020-04-14 11:45:50.414 am infoChecking for updates for Hubitat Package Manager
app:25942020-04-14 11:45:50.262 am infoChecking for updates for MeteoBridge Weather Station
app:25942020-04-14 11:45:50.011 am infoChecking for updates for Hub Watchdog
app:25942020-04-14 11:45:49.915 am debugUpdate chosen
app:25942020-04-14 11:45:42.415 am debugcalled true
app:25942020-04-14 10:28:18.991 am debugcalled false
app:25942020-04-14 10:28:18.760 am debugcalled false
app:25942020-04-14 10:28:18.520 am debugcalled false
app:25942020-04-14 10:28:18.257 am debugcalled false
app:25942020-04-14 10:28:17.936 am debugcalled false
app:25942020-04-14 10:27:59.217 am infoUpgrading Hubitat Package Manager
app:25942020-04-14 10:27:58.972 am infoDownloading Hubitat Package Manager
app:25942020-04-14 10:27:58.625 am debugPerforming update
app:25942020-04-14 10:27:16.588 am infoUpgrading Hubitat Package Manager
app:25942020-04-14 10:27:16.245 am infoDownloading Hubitat Package Manager
app:25942020-04-14 10:27:15.814 am debugPerforming update
app:25942020-04-14 10:27:12.714 am debugprefPkgVerifyUpdates
app:25942020-04-14 10:27:02.295 am debugUpdates available
app:25942020-04-14 10:27:01.688 am debugUpdates found for package https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Follow%20Me/packageManifest.json
app:25942020-04-14 10:27:01.435 am infoChecking for updates for Follow Me
app:25942020-04-14 10:27:01.423 am debugUpdates found for driver https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-sensor.src/ecobee-suite-sensor.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 10:27:01.420 am debugUpdates found for driver https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-thermostat.src/ecobee-suite-thermostat.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 10:27:01.417 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-mode.src/ecobee-suite-smart-mode.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 10:27:01.413 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-circulation.src/ecobee-suite-smart-circulation.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 10:27:01.399 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-routines.src/ecobee-suite-routines.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 10:27:01.395 am debugUpdates found for app https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-open-contacts.src/ecobee-suite-open-contacts.groovy -> https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json
app:25942020-04-14 10:27:01.164 am infoChecking for updates for Ecobee Suite
app:25942020-04-14 10:27:00.961 am infoChecking for updates for PurpleAir Air Quality Station
app:25942020-04-14 10:27:00.951 am debugUpdates found for package https://raw.githubusercontent.com/dcmeglio/hubitat-packagemanager/master/packageManifest.json
app:25942020-04-14 10:27:00.737 am infoChecking for updates for Hubitat Package Manager
app:25942020-04-14 10:27:00.442 am infoChecking for updates for MeteoBridge Weather Station
app:25942020-04-14 10:27:00.210 am infoChecking for updates for Hub Watchdog
app:25942020-04-14 10:27:00.042 am debugUpdate chosen
app:25942020-04-14 10:26:57.742 am debugFound new repository https://raw.githubusercontent.com/RMoRobert/Hubitat/master/repository.json
app:25942020-04-14 10:26:57.488 am debugRefreshing repository list

...

**Comment by dcmeglio** [comment]
I'm not experiencing this, including with the update to Ecobee you put out today. It should NOT be doing this. Here is my best guess looking at the logs, when this was in pre-release I was pushing code to git every couple hours. Perhaps you grabbed it at a point where I had a bug and put it in a bad state. Could you try uninstalling the package manager and reinstalling? You should not need to reinstall any apps/drivers, just run the Match Up feature and everything should be associated properly. Can you try that and let me know if the next time you update ecobee it works fine? As I said, I just updated to the version you pushed out today/yesterday 10 minutes ago and it worked properly for me.

**Comment by SANdood** [comment]
I am suspecting that maybe, if I edit the files after using your installer, that it gets out of sync… Are you doing anything that might break if I edit the files…

**Comment by dcmeglio** [comment]
Nope, it never looks at the contents of the files.

**Comment by SANdood** [comment]
How about the date stamps?

 

I can’t seem to find the REMOVE button for your package manager – I’d like to start over clean… (There is a remove button somewhere, right?)

**Comment by dcmeglio** [comment]
I don't currently have the Remove button shown in app. I'm trying to think of the best place to show it (I don't want people confused on remove a package vs remove the whole thing). However, you can of course always get to the remove button by clicking the gear icon. HE has that remove functionality built in.

**Comment by dcmeglio** [comment]
Think I tracked this down, should be fixed in the next version.
