### ISSUE TITLE
notify app/driver owner of bad manifest

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#49]
I see that BPTWorld has a bad manifest for one of his apps.  Wonder how a notification could occur to the developer to notify them of the error.  Maybe use a free SMTP relay?

**Comment by dcmeglio** [comment]
That sounds a bit scary. Imagine if 1000 people have the app installed, you wouldn't want 1000 emails. I'm thinking the best thought is to encourage people to use the hpm.exe to build the files and to test locally before publishing.

**Comment by bptworld** [comment]
Very scary! I have over 30 apps/drivers.  Typo's WILL happen.  Just need to flush them out as people start using this app.

**Comment by PrayerfulDrop** [comment]
Makes sense not to do this
