### ISSUE TITLE
Fatal error on nulldevice

### ISSUE THREAD

**Issue by SANdood** [dcmeglio/hubitat-packagemanager#53]
I added 6 new optional (required: false) drivers to the Ecobee package.

This causes your version-matching code to fail when you try to run an Update:
 errorjava.lang.NullPointerException: Cannot get property 'version' on null object on line 936 (performUpdateCheck)

The reason is (obviously) because the existing install doesn't have that file installed, so it can't compare versions. I was able to get around the error by changing the code to:
[code]
			for (driver in manifest.drivers) {
				def installedDriver = getDriverById(state.manifests[pkg.key], driver.id)
				if (driver?.version != null && installedDriver?.version != null) {
					if (newVersionAvailable(driver?.version, installedDriver?.version)) {
[/code]
The ?.version won't fail if the target is null. That said, I think you want to be more direct - make it install the new/added item (if required: true), don't flag an error/upgrade if not.

Note that to make this "add a few more optional files" actually work, the user has to re-match the package. I think you need a way that the added items just get melded in, without the user having to do anything.

**Comment by dcmeglio** [comment]
I agree with your fix. Good catch. They wouldn't need to do a match up, they could just go and do a Modify which will list the new optional packages. 

![image](https://user-images.githubusercontent.com/21957250/79483455-55f8ec00-7fe0-11ea-80f9-357549a5a2de.png)

That being said, I agree that's not exactly user friendly. If there are new required ones it should just install them and if there are new optional it should prompt you so you can decide. I'll get on that.

**Comment by SANdood** [comment]
I tried that, and it didn't work - the optional devices didn't show up until I did the re-scan.

**Comment by dcmeglio** [comment]
Hmm I wonder if it didn't work as a result of the first bug, it worked for me. Either way I'm going to build this into the update process because I agree it's confusing right now. I now added support where if there is a new required one it treats it as an upgrade. Now just need to add support for the optional.

**Comment by dcmeglio** [comment]
This will be fixed in the next version.
