### ISSUE TITLE
Suggestion: Use JSON from /device/drivers

### ISSUE THREAD

**Issue by markus-li** [dcmeglio/hubitat-packagemanager#54]
Instead of parsing html, why not use the JSON available at "/device/drivers"? Unfortunately there is no such API for Apps as far as I know.

**Comment by dcmeglio** [comment]
I guess because I didn't know it existed. What page calls that API endpoint?

**Comment by markus-li** [comment]
It's loaded when opening a device page. I would assume for the driver selection list.
