### ISSUE TITLE
Abitily to Unmatch?

### ISSUE THREAD

**Issue by robacarp** [dcmeglio/hubitat-packagemanager#59]
There are a bunch of apps and drivers floating around the hubitat forums. As I poke around trying to find if any of the apps I have installed are hpm providers, I find none. However, I'd still like to take advantage of hpm! If I create a repository, and a manifest file for each of my apps, hpm will (hopefully) happily assume control and all I have to do is tick the version when one of the apps updates.

However......what needs to happen if the author then starts providing an hpm manifest and repository?

**Comment by dcmeglio** [comment]
Good point. Right now you'd have to uninstall and reinstall. However, do you really think hpm provides much value if you have to maintain the manifests yourself?

**Comment by robacarp** [comment]
Well. It wouldn't be hard to make a small web service which creates and updates the manifest files by scanning the static files on github for updates... and I might just (have done that...)!

**Comment by robacarp** [comment]
For my case, I think the easy solution will be to completely nuke packagemanager if the situation ever comes up. It's not a perfect solution, but it'll accomplish the goal without adding complexity to hpm.
