### ISSUE TITLE
Ecobee Suite still shows as available matchup

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#63]
I believe there is a manifest.json issue with the Ecobee Suite.  Everytime I select matchup the Ecobee Suite continues to be available as a possible match.

**Comment by dcmeglio** [comment]
I believe I fixed this in 1.1.0. You need to do that match up once and it should never happen again. There was a bug that was causing it to lose the linkage when you update Ecobee Suite.

**Comment by PrayerfulDrop** [comment]
I am at latest version as of last night.  Did matchuplast night and sync Ecobee.  This morning clicked on matchup to see if other developers have been added yet.  Ecobee showed up again as an app to matchup.

**Comment by dcmeglio** [comment]
Could you show me a screenshot? I'd like to see what specific items it's detecting

**Comment by PrayerfulDrop** [comment]
![HPM](https://user-images.githubusercontent.com/999665/79997855-9bedfe00-847f-11ea-89ce-8b45d8edab71.png)

**Comment by PrayerfulDrop** [comment]
![HPM](https://user-images.githubusercontent.com/999665/79997964-bde78080-847f-11ea-92e8-3a6f59841a33.PNG)

**Comment by PrayerfulDrop** [comment]
on latest version of HPM too

**Comment by dcmeglio** [comment]
Can you try doing a match up one more time? Let's see if it happens the next time Ecobee Suite releases a new version. This is the exact bug I thought I fixed. I'll monitor locally too when Ecobee Suite updates next.

**Comment by PrayerfulDrop** [comment]
How can I tell in the HPM code what version I am on?  Maybe need to add version in the app code comments.

Also, after 3 hours saw BPTWorld had an update.  Went ahead and updated Weather Dot Gov.  No issues there.  Then went to Match Up again and sure enough Ecobee Suite there again.

**Comment by dcmeglio** [comment]
Darn, I have no clue what is causing it and Ecobee Suite is the only app I've had it happen with (though the manifest all looks fine!). I'll dig in some more. Did it again say it was the thermostat and sensor or did it list something else?

In the next version the View Apps/Drivers will show all version #s, including for HPM.

**Comment by PrayerfulDrop** [comment]
Same as above image

**Comment by dcmeglio** [comment]
I found one small thing but I don't think it would cause this. I will keep digging.

**Comment by PrayerfulDrop** [comment]
Looks as though HPM did not update correctly.  This COULD be because I was on the alpha code and did not input the beta code.  After updating to current HPM code version I don't have these issues.  Again it would be wise to add version # in your code comments in the HPM.groovy file itself as a manual confirmation that someone has updated accordingly.

**Comment by PrayerfulDrop** [comment]
UGH!!  Nevermind Ecobee Suite still showing up in the matching process.  :(

![HPM](https://user-images.githubusercontent.com/999665/80237848-01c6bb00-8623-11ea-976c-13b6a92774be.PNG)

**Comment by dcmeglio** [comment]
Hmm did you do anything recently? Trying to find the cause. Update an app, install something? whatever? Just trying to think what might have caused it.

**Comment by PrayerfulDrop** [comment]
There is (4) new developers.  I wanted to matchup potential apps/drivers I am using.  That is why I did the match update.

**Comment by dcmeglio** [comment]
So basically you don't think you did anything recently, just came in and did a match up? Could you show the "manifests" variable from the app state screen? There's nothing confidential in there other than it will list which packages you have installed. I want to see why it doesn't think it's already installed.

One last thing that could cause it, and it was from an old bug,.. any chance there are duplicates of those two drivers in Drivers Code? I fixed that a long time ago, but basically it was creating dups at one point and then the Match Up toggles back and forth between which one it matches up to.

**Comment by PrayerfulDrop** [comment]
I do see duplicates in the drivers but not apps.

{https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/drivers/salt.json={author=Aaron Ward, packageName=Salt Tank MQTT Driver, version=1.0.6, drivers=[{name=Salt Tank Device, namespace=aaronward, heID=2539, location=https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/drivers/Salt%20Tank.groovy, id=94d2fe65-12a1-4074-934e-6bf7eef1bd96, oauth=false, version=1.0.6, required=true}]}, https://raw.githubusercontent.com/DaveGut/HubitatActive/master/SamsungMultiroom/packageManifest.json={author=Dave Gutheinz, packageName=Samsung MultiRoom Speakers, version=3.1.0, drivers=[{name=Samsung Wifi Speaker, namespace=davegut, heID=536, location=https://raw.githubusercontent.com/DaveGut/HubitatActive/master/SamsungMultiroom/MultiRoomDriver.groovy, id=689ef827-5405-41ea-98eb-79688af0ddd8, required=true}], apps=[{name=Samsung Speakers Integration, namespace=davegut, heID=393, location=https://raw.githubusercontent.com/DaveGut/HubitatActive/master/SamsungMultiroom/MultiRoomApp.groovy, id=5cce274d-6d84-4a56-8533-6e4a61691242, oauth=false, required=true}]}, https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Magic%20Cube/packageManifest.json={author=BPTWorld, packageName=Magic Cube, drivers=[], apps=[{name=Magic Cube, namespace=BPTWorld, heID=1128, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Magic%20Cube/MC-parent.groovy, id=3fe7903d-280e-46f4-8720-2f621c59093e, oauth=false, version=2.0.0, required=true}, {name=Magic Cube Child, namespace=BPTWorld, heID=1129, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Magic%20Cube/MC-child.groovy, id=e90b111f-6c45-42f5-a74f-0f65e65d3ec2, oauth=false, version=2.0.1, required=true}]}, https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/You%20Got%20Mail/packageManifest.json={author=Aaron Ward, packageName=You Got Mail, version=1.0.6, apps=[{name=You Got Mail, namespace=aaronward, heID=1608, location=https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/You%20Got%20Mail/yougotmail.groovy, id=094f56a9-44f3-48a2-a698-4de5f1de66e1, oauth=false, version=1.0.6, required=true}]}, https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/drivers/eco.json={author=Aaron Ward, packageName=EcoLink Contact Sensor Custom, version=1.0.1, drivers=[{name=Ecolink Contact Sensor Custom, namespace=aaronward, heID=2307, location=https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/drivers/ecolink-custom.groovy, id=06cd7d68-2108-4842-8f83-b977fd4fa8c3, oauth=false, version=1.0.1, required=true}]}, https://raw.githubusercontent.com/dcmeglio/hubitat-rebooter/master/packageManifest.json={author=Dominick Meglio, documentationLink=https://github.com/dcmeglio/hubitat-rebooter/blob/master/README.md, packageName=Hub Rebooter, version=1.0.1, communityLink=https://community.hubitat.com/t/release-hub-rebooter-app/30310, apps=[{name=Rebooter, namespace=dcm.rebooter, heID=2280, location=https://raw.githubusercontent.com/dcmeglio/hubitat-rebooter/master/apps/Rebooter.groovy, id=d7b86d78-087c-4ec9-b278-dd4f376193dc, required=true}]}, https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/Roomba/packageManifest.json={author=Aaron Ward, packageName=iRobot Scheduler, version=1.3.5, drivers=[{name=Roomba, namespace=roomba, heID=2435, location=https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/Roomba/Roomba-device.groovy, id=ee4f2c21-6ec9-455b-b426-2276c1e84fe8, version=1.1.6, required=true}], apps=[{name=iRobot Scheduler, namespace=aaronward, heID=2184, location=https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/Roomba/Roomba-app.groovy, id=14d00d83-9eb1-47f2-87ed-07bc81b39f34, oauth=false, version=1.3.5, required=true}]}, https://raw.githubusercontent.com/Scottma61/Hubitat/master/docs/DS_packageManifest.json={author=Matthew Scott, documentationLink=https://github.com/HubitatCommunity/DarkSky.net-Weather-Driver/wiki/Welcome-to-the-DarkSky.net-Weather-Driver-wiki!, packageName=DarkSky.net Weather Driver, version=1.4.1, drivers=[{name=DarkSky.net Weather Driver, namespace=Matthew, heID=2501, location=https://raw.githubusercontent.com/HubitatCommunity/DarkSky.net-Weather-Driver/master/DarkSky.net%20Weather%20Driver.groovy, id=e1c6b958-9b02-4b50-ac5d-5cb64ad545aa, required=true}], communityLink=https://community.hubitat.com/t/release-darksky-net-weather-driver-no-pws-required/22699}, https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/NOAA/packageManifest.json={author=Aaron Ward, packageName=NOAA Weather Alerts, drivers=[{name=NOAA Tile, namespace=aaronward, heID=1603, location=https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/NOAA/NOAA-Tile-Driver.groovy, id=68115e5c-d300-430e-afb3-277b61554946, version=1.2.2, required=true}], apps=[{name=NOAA Weather Alerts, namespace=aaronward, heID=2472, location=https://raw.githubusercontent.com/PrayerfulDrop/Hubitat/master/NOAA/NOAA-Severe-Weather.groovy, id=82a848f3-e61c-429e-b557-2019b559f509, oauth=false, version=2.5.3, required=true}]}, https://raw.githubusercontent.com/dcmeglio/hubitat-packagemanager/master/packageManifest.json={author=Dominick Meglio, documentationLink=https://github.com/dcmeglio/hubitat-packagemanager/blob/master/README.md, packageName=Hubitat Package Manager, version=1.1.1, communityLink=https://community.hubitat.com/t/beta-hubitat-package-manager/38016, apps=[{name=Hubitat Package Manager, heID=2344, location=https://raw.githubusercontent.com/dcmeglio/hubitat-packagemanager/master/apps/Package_Manager.groovy, id=2e6b1674-a87b-41a8-bd65-5cbbf78d842e, required=true}]}, https://raw.githubusercontent.com/SANdood/PurpleAirStation/master/packageManifest.json={author=Barry A. Burke, packageName=PurpleAir Air Quality Station, version=1.1.08, drivers=[{name=PurpleAir Air Quality Station, namespace=sandood, heID=1795, location=https://raw.githubusercontent.com/SANdood/PurpleAirStation/master/devicetypes/sandood/purpleair-air-quality-station.src/purpleair-air-quality-station.groovy, id=6a725f19-a77f-4d3e-9615-cce0d4834cb7, required=true}]}, https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/packageManifest.json={author=Barry A. Burke, packageName=Ecobee Suite, drivers=[{name=Ecobee Suite Thermostat, namespace=sandood, heID=3171, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-thermostat.src/ecobee-suite-thermostat.groovy, id=78e479a2-7fe8-4b92-94b2-5784b66e6086, version=1.8.13, required=true}, {name=Ecobee Suite Sensor, namespace=sandood, heID=3107, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-sensor.src/ecobee-suite-sensor.groovy, id=1a8e591e-ca09-43da-9695-745eb7ceb625, version=1.8.07, required=true}, {name=EcoNet Vent, namespace=sandood, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/EcoNet%20Vent.groovy, id=71a545f8-bfe1-4cff-aeb3-59f5bde16e6d, version=1.8.01, required=false}, {name=HubConnect EcoVent, namespace=shackrat, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/HubConnect%20%20EcoVent.groovy, id=c4cadeb4-91e1-48f6-85a4-fb963fd57559, version=1.8.01, required=false}, {name=Keen Home Smart Vent, namespace=sandood, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/Keen%20Home%20Smart%20Vent.groovy, id=abe02ac0-14e1-43ce-a867-502f470be79c, version=1.8.01, required=false}, {name=HubConnect Keen Home Smart Vent, namespace=shackrat, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/HubConnect%20Keen%20Home%20Smart%20Vent.groovy, id=71ea8020-77d5-4776-b8ae-6d491ea724b5, version=1.8.01, required=false}, {name=HubConnect Ecobee Suite Thermostat, namespace=shackrat, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/HubConnect-Ecobee-Suite-Thermostat.groovy, id=1ca88f35-538e-462e-aa51-cad12f8e83d1, version=1.8.01, required=false}, {name=HubConnect Ecobee Suite Sensor, namespace=shackrat, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/HubConnect/Universal/Custom-Drivers/HubConnect-Ecobee-Suite-Sensor.groovy, id=26a62a35-374b-494b-9337-069fd324f441, version=1.8.01, required=false}], apps=[{name=Ecobee Suite Manager, namespace=sandood, heID=2440, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-manager.src/ecobee-suite-manager.groovy, id=70b3ec47-c06f-4570-b4ae-5ee76da59db8, oauth=true, version=1.8.34, required=true}, {name=ecobee Suite Open Contacts, namespace=sandood, heID=2441, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-open-contacts.src/ecobee-suite-open-contacts.groovy, id=79adb376-0b4d-4e3d-b20e-bcc557fdd15d, oauth=false, version=1.8.19, required=true}, {name=ecobee Suite Quiet Time, namespace=sandood, heID=2442, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-quiet-time.src/ecobee-suite-quiet-time.groovy, id=74d41ded-9a35-4916-98e3-2309364b477b, oauth=false, version=1.8.06, required=true}, {name=ecobee Suite Routines, namespace=sandood, heID=2443, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-routines.src/ecobee-suite-routines.groovy, id=c630b027-9cdf-49ff-bff6-28ced385a9e2, oauth=false, version=1.8.12, required=true}, {name=ecobee Suite Smart Circulation, namespace=sandood, heID=2444, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-circulation.src/ecobee-suite-smart-circulation.groovy, id=cc05b8d1-01b7-449e-b12b-9f56ccbdf23c, oauth=false, version=1.8.08, required=true}, {name=ecobee Suite Smart Humidity, namespace=sandood, heID=2445, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-humidity.src/ecobee-suite-smart-humidity.groovy, id=d14d22cf-bdb4-4d12-8c89-ac849a5e0e53, oauth=false, version=1.8.07, required=true}, {name=ecobee Suite Smart Mode, namespace=sandood, heID=2446, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-mode.src/ecobee-suite-smart-mode.groovy, id=7d7849d3-333f-4782-b52b-4f910bf5380f, oauth=false, version=1.8.16, required=true}, {name=ecobee Suite Smart Room, namespace=sandood, heID=2447, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-room.src/ecobee-suite-smart-room.groovy, id=8d9d8751-6679-4581-b594-41549106c789, oauth=false, version=1.8.12, required=true}, {name=ecobee Suite Smart Switches, namespace=sandood, heID=2448, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-switches.src/ecobee-suite-smart-switches.groovy, id=a07da3bd-6638-4d9a-a739-4efc37273095, oauth=false, version=1.8.06, required=true}, {name=ecobee Suite Smart Vents, namespace=sandood, heID=2449, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-vents.src/ecobee-suite-smart-vents.groovy, id=e60053c8-a397-4231-ba7f-59ef23505740, oauth=false, version=1.8.09, required=true}, {name=ecobee Suite Smart Zones, namespace=sandood, heID=2450, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-smart-zones.src/ecobee-suite-smart-zones.groovy, id=329710ed-0ee3-41a6-9e47-f04b7a6174a6, oauth=false, version=1.8.08, required=true}, {name=ecobee Suite Thermal Comfort, namespace=sandood, heID=2451, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-thermal-comfort.src/ecobee-suite-thermal-comfort.groovy, id=487d8dde-077c-4ae3-b17b-180039b3e59d, oauth=false, version=1.8.11, required=true}, {name=ecobee Suite Working From Home, namespace=sandood, heID=2452, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/smartapps/sandood/ecobee-suite-working-from-home.src/ecobee-suite-working-from-home.groovy, id=1438882b-2411-406d-a831-997c4b569c31, oauth=false, version=1.8.12, required=true}]}, https://raw.githubusercontent.com/bptworld/Hubitat/master/Ported/Life360/packageManifest.json={author=BPTWorld, packageName=Life360 with States, drivers=[{name=Location Tracker User Driver, namespace=BPTWorld, heID=3046, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Ported/Life360/L-driver.groovy, id=a01994ba-1888-4716-b118-1d2184dc2b44, version=1.0.1, required=true}], apps=[{name=Life360 with States, namespace=BPTWorld, heID=1673, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Ported/Life360/L-app.groovy, id=e96d12be-d8ba-4337-b71d-f1be59bf2cd4, oauth=false, version=2.0.4, required=true}]}, https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Weather%20Dot%20Gov/packageManifest.json={author=BPTWorld, packageName=Weather Dot Gov, drivers=[{name=Weather Dot Gov Data Driver, namespace=BPTWorld, heID=3139, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Weather%20Dot%20Gov/WDG-data-driver.groovy, id=7594675a-a13d-40b5-a134-516ac87a1aec, version=1.1.0, required=true}, {name=Weather Dot Gov Tile Driver, namespace=BPTWorld, heID=3140, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Weather%20Dot%20Gov/WDG-tile-driver.groovy, id=cdba29b5-e871-44a0-87c2-9aad1f340763, version=1.0.3, required=true}], apps=[{name=Weather Dot Gov, namespace=BPTWorld, heID=2536, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Weather%20Dot%20Gov/WDG-parent.groovy, id=5d3ba06b-e58d-403c-b3fb-17a239ed2f4c, oauth=false, version=1.0.0, required=true}, {name=Weather Dot Gov Child, namespace=BPTWorld, heID=2537, location=https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Weather%20Dot%20Gov/WDG-child.groovy, id=aa24dff0-9a3e-41c6-a6c4-adf244ceece2, oauth=false, version=1.1.0, required=true}]}}

**Comment by dcmeglio** [comment]
Ok that's the problem:

[{name=Ecobee Suite Thermostat, namespace=sandood, heID=3171, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-thermostat.src/ecobee-suite-thermostat.groovy, id=78e479a2-7fe8-4b92-94b2-5784b66e6086, version=1.8.13, required=true}, {name=Ecobee Suite Sensor, namespace=sandood, heID=3107, location=https://raw.githubusercontent.com/SANdood/Ecobee-Suite/master/devicetypes/sandood/ecobee-suite-sensor.src/ecobee-suite-sensor.groovy, id=1a8e591e-ca09-43da-9695-745eb7ceb625, version=1.8.07, required=true}, 

It's currently associated with 3171 and 3107. Are those the "real ones" or are the ones with different IDs the ones that are in use? If those are the real ones, just delete the other dups. If they aren't do a match up, which should switch it to the other ids, then delete the 3171/3107.

It shouldn't happen again, I resolved this bug already but didn't have a good way to clean up if it already occurred. It actually happened to me with your Roobma driver.

**Comment by PrayerfulDrop** [comment]
Had to move all the devices over to the other driver prior to deletion but all good now!
