### ISSUE TITLE
Possible bug: Adding a custom repo

### ISSUE THREAD

**Issue by robacarp** [dcmeglio/hubitat-packagemanager#77]
Fresh install of package manager, no packages matched and no settings changed.

Main menu -> package manager settings -> add custom repository -> paste repository url

When I click next the Available Repositories field is highlighted red, and an alert shows up with the message. "Required Fields missing or not passing validation. Please check red underlined fields and complete the required fields (ones with *)" It's not obvious to me how to proceed, but even checking that all the options under Available Repositories are checked I wasn't able to move forward.

**Comment by dcmeglio** [comment]
I just tested and it worked for me. I suspect there are other required fields on the page that you didn't fill out, namely the "Specify what time update checking should be performed*" text box. Can you confirm that you did have a value entered for this?

**Comment by robacarp** [comment]
![image](https://user-images.githubusercontent.com/208647/80733686-4347e200-8acb-11ea-9688-17534e35c18f.png)

I didn't touch those fields, and they didn't get marked red so I didn't even notice them. You're right that putting a value in them allowed me to continue though. Thanks for checking!

**Comment by dcmeglio** [comment]
Weird, in your browser HE doesn't show the time picker in red... That would be an HE issue though, I don't have control over that. Glad it's working now!
