### ISSUE TITLE
Errors with split() code on line 2241

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#79]
HPM 1.3.0 has issues:
app:51652020-05-01 10:41:55.838 am errorjava.lang.NullPointerException: Cannot invoke method size() on null object on line 2240 (performUpdateCheck)
app:51652020-05-01 10:41:55.771 am infoChecking for updates for NOAA Weather Alerts
app:51652020-05-01 10:41:55.694 am infoChecking for updates for DarkSky.net Weather Driver
app:51652020-05-01 10:41:55.627 am infoChecking for updates for iRobot Scheduler
app:51652020-05-01 10:41:55.561 am infoChecking for updates for Hub Rebooter
app:51652020-05-01 10:41:55.484 am infoChecking for updates for EcoLink Contact Sensor Custom
app:51652020-05-01 10:41:55.407 am infoChecking for updates for You Got Mail
app:51652020-05-01 10:41:55.338 am infoChecking for updates for Kasa Plugs, Switches and Bulbs
app:51652020-05-01 10:41:55.264 am infoChecking for updates for Magic Cube
app:51652020-05-01 10:41:55.185 am infoChecking for updates for Samsung MultiRoom Speakers
app:51652020-05-01 10:41:55.037 am infoChecking for updates for Salt Tank MQTT Driver

Not sure if this my packageManifest.json file or the code.

**Comment by PrayerfulDrop** [comment]
Recommended addition of code:

def newVersionAvailable(item, installedItem) {
    try {
	def versionStr = includeBetas && item.betaVersion != null ? item?.betaVersion : item?.version
	def installedVersionStr = installedItem.beta ? installedItem?.betaVersion : installedItem?.version
	if (versionStr == null)
		return false
	versionStr = versionStr.replaceAll("[^\\d.]", "")
    installedVersionStr = installedVersionStr?.replaceAll("[^\\d.]", "")
	def installedVersionParts = installedVersionStr?.split(/\./)
	def newVersionParts = versionStr.split(/\./)

	for (def i = 0; i < newVersionParts.size(); i++) {
		if (i >= installedVersionParts.size()) {
			return true
		}
		def installedPart = installedVersionParts[i].toInteger()
		def newPart = newVersionParts[i].toInteger()
		if (installedPart < newPart) {
			return true
		}
	}
	if (versionStr == installedVersionStr && installedItem?.beta && versionStr == item?.version)
		return true
	return false 
    }
    catch (e) { log.error "${e}"
               return false }
}

**Comment by dcmeglio** [comment]
Trying to track down the root cause, is NOAA Weather Alerts something you have installed?

**Comment by PrayerfulDrop** [comment]
Yes of course I do.  I authored the app.  :)

https://github.com/PrayerfulDrop/Hubitat/tree/master/NOAA

I didn't have any of these issues until a couple days ago.  I did update the manifest but didn't see any errors.

**Comment by dcmeglio** [comment]
I may need some help troubleshooting. I’ll add some logging code so we can see what’s going on. It works for me with your app.

**Comment by PrayerfulDrop** [comment]
yeah getting errors.  I can delete HPM and reinstall.  Maybe a state variable is set incorrectly?

**Comment by dcmeglio** [comment]
Or something weird is broken. I will be home in 20 mins and will add some debug logging to see if we can find it

**Comment by PrayerfulDrop** [comment]
If I add the try to the newVersionAvailable(item, installedItem) subroutine it gets by without issues.  Maybe my json package is messed up?

**Comment by PrayerfulDrop** [comment]
Ugh ok now it is working after doing an "install" in HPM which forces a refresh of the manifests and then doing an update.  Might want to force the manifest updates when "update" is selected.
