### ISSUE TITLE
1.3.2 update error

### ISSUE THREAD

**Issue by CurtisZM** [dcmeglio/hubitat-packagemanager#81]
I did the 1.3.2 update. Completed the update, clicked on next and then an unexpected error. I went back after a minute and now everything is fine.

2020-05-01 06:35:54.421 pm errorjava.lang.NullPointerException: Cannot get property 'location' on null object on line 2709 (prefOptions)
app:48122020-05-01 06:35:50.244 pm debugUpdates complete
app:48122020-05-01 06:35:35.072 pm infoUpgrading Hubitat Package Manager
app:48122020-05-01 06:35:34.612 pm infoDownloading Hubitat Package Manager
app:48122020-05-01 06:35:34.165 pm debugPerforming update
app:48122020-05-01 06:35:31.744 pm debugprefPkgVerifyUpdates
app:48122020-05-01 06:35:30.417 pm debugUpdates available
app:48122020-05-01 06:35:27.351 pm debugUpdates available
app:48122020-05-01 06:35:26.114 pm infoChecking for updates for Weather Dot Gov
app:48122020-05-01 06:35:25.753 pm infoChecking for updates for Device Check Plus
app:48122020-05-01 06:35:25.446 pm infoChecking for updates for Remote Wellness Check
app:48122020-05-01 06:35:24.971 pm infoChecking for updates for Follow Me
app:48122020-05-01 06:35:24.667 pm infoChecking for updates for CATT Director
app:48122020-05-01 06:35:24.343 pm infoChecking for updates for BI Control
app:48122020-05-01 06:35:24.002 pm infoChecking for updates for Life360 with States
app:48122020-05-01 06:35:23.999 pm debugUpdates found package for https://raw.githubusercontent.com/dcmeglio/hubitat-packagemanager/master/packageManifest.json -> null
app:48122020-05-01 06:35:23.991 pm debugUpdates found for package https://raw.githubusercontent.com/dcmeglio/hubitat-packagemanager/master/packageManifest.json
app:48122020-05-01 06:35:23.667 pm infoChecking for updates for Hubitat Package Manager
app:48122020-05-01 06:35:23.303 pm infoChecking for updates for NOAA Weather Alerts
app:48122020-05-01 06:35:22.947 pm infoChecking for updates for Weather-Display With OWM-NWS Alerts Forecast Driver
app:48122020-05-01 06:35:22.633 pm infoChecking for updates for OpenWeatherMap-NWS Alerts Weather Driver
app:48122020-05-01 06:35:22.404 pm infoChecking for updates for Life360 Tracker
app:48122020-05-01 06:35:22.148 pm infoChecking for updates for Hub Watchdog
app:48122020-05-01 06:35:21.911 pm infoChecking for updates for Presence Plus
app:48122020-05-01 06:35:21.605 pm infoChecking for updates for Device Watchdog
app:48122020-05-01 06:35:21.390 pm infoChecking for updates for The Flasher
app:48122020-05-01 06:35:21.100 pm infoChecking for updates for Hub Rebooter
app:48122020-05-01 06:35:20.793 pm infoChecking for updates for Simple Dates
app:48122020-05-01 06:35:20.486 pm infoChecking for updates for Chromecast Helper
app:48122020-05-01 06:35:20.177 pm infoChecking for updates for Simple Kitchen Timer
app:48122020-05-01 06:35:19.884 pm infoChecking for updates for Room Director
app:48122020-05-01 06:35:19.577 pm infoChecking for updates for Google Home Community
app:48122020-05-01 06:35:19.266 pm infoChecking for updates for Tile Master
app:48122020-05-01 06:35:19.125 pm debugUpdate chosen
app:48122020-05-01 06:35:13.897 pm debugRefreshing repository list

**Comment by dcmeglio** [comment]
Thanks, I see what the problem is here.
