### ISSUE TITLE
Issue installing "Tasmota for Hubitat Elevation"

### ISSUE THREAD

**Issue by SebastienViel** [dcmeglio/hubitat-packagemanager#86]
Trying to install the "Tasmota for Hubitat Elevation" integration app from Markus, I get the following error:

> app:442020-05-10 10:46:54.905 errorjava.lang.NullPointerException: Cannot get property 'betaLocation' on null object on line 2822 (performInstallation)
> app:442020-05-10 10:46:54.297 infoDownloading Tasmota - Universal Parent
> app:442020-05-10 10:46:53.819 infoDownloading Tasmota Device Manager
> app:442020-05-10 10:46:53.444 debugInstall beginning

Is this an issue with the Package manager or with the Tasmota app?

**Comment by dcmeglio** [comment]
Do you know which of the drivers you checked off during install? I want to try to reproduce it.

**Comment by SebastienViel** [comment]
Yes, I selected 2.  The Universal CT/RGB/RGB+CW+WW and Universal Metering Plug childs.

**Comment by dcmeglio** [comment]
Thanks, I figured it out. It will be fixed in 1.4.0 which I hope to release later today.

**Comment by SebastienViel** [comment]
Awesome!  :-)
