### ISSUE TITLE
Install: List by Developer

### ISSUE THREAD

**Issue by PrayerfulDrop** [dcmeglio/hubitat-packagemanager#88]
Search and categories are awesome. Would even be better to search or list apps to install by developer.

**Comment by dcmeglio** [comment]
Could you help me understand the use case? It's doable, I'm just wondering, do you think users care who the developer was? Meaning we're not talking about Dev A = Microsoft and Dev B = Some Shady Guy Software Co. We're all the "little guy". Do you think users will want to search by developer? I'm wondering if most people even have a clue who developed what :)

**Comment by PrayerfulDrop** [comment]
Yes they do. There are apps I remember from past by the developer but do not remember the app name. There are developers like Cobra and BPtWorld that have a ton of apps. Nice to list apps quickly based on the developer themselves. Also agree with BPTWorld and his suggestion for HE community name.

**Comment by dcmeglio** [comment]
Instead of adding an additional option, thoughts on just allowing the
search feature to let you search by author name?

**Comment by PrayerfulDrop** [comment]
Yeah might work

**Comment by PrayerfulDrop** [comment]
Actually a better option would be to have the developer name available as a valid search category

**Comment by dcmeglio** [comment]
You can now search by developer name. Good news, this was just a back end Azure change so it's already available, no new version of HPM needed.
