### ISSUE TITLE
Can't save settings. Not passing validation.

### ISSUE THREAD

**Issue by dzerovibe** [dcmeglio/hubitat-packagemanager#95]
I was just trying to enable auto updates in my Package Manager, and after changing the settings that I wanted, I clicked "Next" but I got the popup shown in the attached screenshot. As you can see, the fields that are highlighted red are in fact filled out correctly. I tried various permutations of settings, but I keep getting the same error. I even tried coming back to the Settings page and, without changing anything, just clicking on Next. It still gives me the error.

I've just updated to the latest version of HPM (1.4.1) but that didn't help.

As it stands now, I can't change any of my settings. eg. Trying to select more repositories.

<img width="1440" alt="Screen Shot 2020-05-17 at 19 05 33" src="https://user-images.githubusercontent.com/169719/82140231-ada1a600-9871-11ea-8f40-ab096f2fe488.png">

**Comment by dcmeglio** [comment]
It’s not in your image but I’m 99% sure you didn’t fill in the time for the update checker to run.

**Comment by dzerovibe** [comment]
Ah, you're absolutely correct! :-) I never even looked at those fields, since they weren't being highlighted in red. So I guess there's just a bug in the field validation. Is that in your own code, or Hubitat's?

![Screen Shot 2020-05-17 at 23 43 55](https://user-images.githubusercontent.com/169719/82148951-c2456480-9898-11ea-98d9-795a4f01d844.png)

**Comment by dcmeglio** [comment]
Unfortunately it is an HE issue as far as I can tell. It only happens because you're in 24 hour time. Their control for 12 hour time does show in red. I reported this to the HE team but they said it's pretty low priority which I understand. I'm trying to find a way to work around it because several people have been confused.

**Comment by dzerovibe** [comment]
Fair enough. But what about the fields that were incorrectly marked as invalid? Is that a by-product of the same bug?

**Comment by dzerovibe** [comment]
Actually, I've just gone and read through more of the forum thread, and I can see that you've discussed it a bit over there.
