### ISSUE TITLE
Add ability to remove custom repository settings/state

### ISSUE THREAD

**Issue by imnotbob** [dcmeglio/hubitat-packagemanager#96]
How to remove custom repos?

**Comment by dcmeglio** [comment]
You should be able to uncheck them like any repo, but you're right, currently there was no way to remove them from the list entirely

**Comment by neonturbo** [comment]
If you wanted to manually remove them by editing the app code, is that possible? If so, about where (line number?) in the code is this stored?

**Comment by dcmeglio** [comment]
It's not in the code, it's stored in a state variable. You'd need to write code to modify that variable.

**Comment by neonturbo** [comment]
Ah, thanks.

Please consider adding this capability.

**Comment by dcmeglio** [comment]
Custom repositories will include a "Remove" button in 1.5.0
